packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.66.9
  "@trpc/client": ^11.0.0-rc.772
  "@trpc/tanstack-react-query": ^11.0.0-rc.772
  "@trpc/server": ^11.0.0-rc.772
  "@types/node": ^22.10.7
  eslint: ^9.19.0
  prettier: ^3.4.2
  "react-hook-form": ^7.54.2
  tailwindcss: ^3.4.14
  typescript: ^5.7.3
  zod: ^3.24.1
  dotenv-cli: ^8.0.0
  sonner: ^2.0.1

catalogs:
  react:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  next:
    next: 15.1.6
  auth:
    better-auth: ^1.1.16
